POST https://to-do-list-ppj7.onrender.com/tasks
Content-type: application/json

{
    "name": "jkjkjkjkkj",
    "cost": 3000,
    "deadline": "2022-03-27"
}

### 


GET https://to-do-list-ppj7.onrender.com/tasks


### 


PUT https://to-do-list-ppj7.onrender.com/tasks/e9c791a2-9c76-4417-ba35-d5aa71fdb489
Content-type: application/json

{
    "name": "tarefa 02",
    "cost": 11900,
    "deadline": "2024-10-19"
}

### 


DELETE https://to-do-list-ppj7.onrender.com/tasks/178998

