POST https://to-do-list-ppj7.onrender.com/tasks
Content-type: application/json

{
    "name": "Esta frase possui exatamente 141 caracteres, o que significa que ela ultrapassa o limite de 140 caracteres permitido para certos campos de entrada.",
    "cost": 99999999,
    "deadline": "2022-03-27"
}

### 


GET https://to-do-list-ppj7.onrender.com/tasks


### 


PUT https://to-do-list-ppj7.onrender.com/tasks/284c7422-413b-4f98-b56c-c8d01c0d4da7
Content-type: application/json

{
    "name": "tarefa 02",
    "cost": 900,
    "deadline": "2024-10-19"
}

### 


DELETE https://to-do-list-ppj7.onrender.com/tasks/284c7422-413b-4f98-b56c-c8d01c0d4da7